BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB

BBBB BBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBB

    XXXX gettext(u'Log in') XXXXX

    XXXXX XXXXXXXXXXXXXX

        BBBBBBBBBB
        BBBBBBBBBBBBBB BBBB

        XXXXXXX XXXXXXXXXX XXXXXXXXXXXXX gettext(u'Log in') XXXXXXXXX

    XXXXXXX

    XXXX

    XXXX
        XXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBXX gettext(u'Forgot your password?') XXXX
        XXXXX
        XXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBXX gettext(u'Forgot your username?') XXXX
        XXXXX
        XXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX gettext(u'Resend an activation code') XXXX
        XXXXX
    XXXXX

BBBBBBBB
