BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB

BBBB BBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBB

    XXXX gettext(u'Resend an activation code') XXXXX

    XXXXX XXXXXXXXXXXXXX

        BBBBBBBBBB
        BBBBBBBBBBBBBB BBBB

        XXXXXXX XXXXXXXXXX XXXXXXXXXXXXX gettext(u'Next') XXXXXXXXX

    XXXXXXX

    XXXX

    XXXX
        XXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBXX gettext(u'Log in') XXXX
        XXXXX
    XXXXX

BBBBBBBB
