BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB

BBBB BBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBB

    XXXX gettext(u'Create an account') XXXXX

    XXXXX XXXXXXXXXXXXXX

        BBBBBBBBBB
        BBBBBBBBBBBBBB BBBB

        XXXXXXX XXXXXXXXXX XXXXXXXXXXXXX gettext(u'Create') XXXXXXXXX

    XXXXXXX

BBBBBBBB
