# Generated by Django 2.0 on 2017-12-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activation',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
