BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB

BBBB BBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBB

    XXXX gettext(u'Change email') XXXXX

    XXXXX XXXXXXXXXXXXXX

        BBBBBBBBBB
        BBBBBBBBBBBBBB BBBB

        XXXXXXX XXXXXXXXXX XXXXXXXXXXXXX gettext(u'Change') XXXXXXXXX

    XXXXXXX

BBBBBBBB
